version: "3.7"

services:
  postgres:
    image: postgres:12
    ports:
      - "2345:2345"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./data:/var/lib/postgresql/data
